services:
  app:
    build: .
    container_name: demo-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"